name: Feature
description: New capability or improvement
labels: ["type:feature"]
body:
  - type: input
    id: summary
    attributes: { label: One-sentence outcome }
  - type: textarea
    id: context
    attributes: { label: Context/links (Archon brief, ADR) }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (testable)
      description: Bullet list; becomes DoD for PR & agents
  - type: dropdown
    id: size
    attributes: { label: Size (expected), options: [XS,S,M,L] }
  - type: dropdown
    id: priority
    attributes: { label: Priority, options: [P0,P1,P2,P3] }
